apiVersion: v1 # Kubernetes API version
kind: Service # Resource type
metadata: # Object metadata
  name: grafana # Service name
  namespace: monitoring # Target namespace
spec:
  selector: # Pod selector
    app: grafana # Match label
  ports:
    - port: 3000 # Service port
      targetPort: 3000 # Container port
