apiVersion: v1 # Kubernetes API version
kind: Service # Resource type
metadata: # Object metadata
  name: prometheus # Service name
  namespace: monitoring # Target namespace
spec:
  selector: # Pod selector
    app: prometheus # Match label
  ports:
    - port: 9090 # Service port
      targetPort: 9090 # Container port
